# Generated by packaging/homebrew.sh in cloudcons/deconflict-cli on each
# release. Edits here are overwritten by the next one.
class Deconflict < Formula
  desc "Advisory intention claims and negotiated agreements for coding agents"
  homepage "https://github.com/cloudcons/deconflict-cli"
  version "0.1.8"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/cloudcons/deconflict-cli/releases/download/v0.1.8/deconflict_0.1.8_darwin_arm64.tar.gz"
      sha256 "6062ae9e1d5726b2c9ab461a2fcc136dcbfaa021577d77e6b52c32884413fc1f"
    end
    on_intel do
      url "https://github.com/cloudcons/deconflict-cli/releases/download/v0.1.8/deconflict_0.1.8_darwin_amd64.tar.gz"
      sha256 "58767f31a66e78e2e80b5c2db808405404769b75b601fd5df3d44bbb2905d012"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/cloudcons/deconflict-cli/releases/download/v0.1.8/deconflict_0.1.8_linux_arm64.tar.gz"
      sha256 "2452631a4d30597a66109226f51405ec64c394f87e72198cea3cabae6107427d"
    end
    on_intel do
      url "https://github.com/cloudcons/deconflict-cli/releases/download/v0.1.8/deconflict_0.1.8_linux_amd64.tar.gz"
      sha256 "f31362361b240a8542a571fef1d040ac8f0833b62d825afb2352c8649b83aee5"
    end
  end

  def install
    bin.install "deconflict"
  end

  def caveats
    <<~EOS
      Wire deconflict into the coding agents you run with:
        deconflict install --agent all
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/deconflict version")
  end
end
